/*
NiFi Rest API

The Rest API provides programmatic access to command and control a NiFi instance in real time. Start and                                             stop processors, monitor queues, query provenance data, and more. Each endpoint below includes a description,                                             definitions of the expected input and output, potential response codes, and the authorizations required                                             to invoke each service.

API version: 2.0.0
Contact: dev@nifi.apache.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nifiapi

import (
	"encoding/json"
)

// checks if the UpdateControllerServiceReferenceRequestEntity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateControllerServiceReferenceRequestEntity{}

// UpdateControllerServiceReferenceRequestEntity struct for UpdateControllerServiceReferenceRequestEntity
type UpdateControllerServiceReferenceRequestEntity struct {
	// The identifier of the Controller Service.
	Id *string `json:"id,omitempty"`
	// The new state of the references for the controller service.
	State *string `json:"state,omitempty"`
	// The revisions for all referencing components.
	ReferencingComponentRevisions *map[string]RevisionDTO `json:"referencingComponentRevisions,omitempty"`
	// Acknowledges that this node is disconnected to allow for mutable requests to proceed.
	DisconnectedNodeAcknowledged *bool `json:"disconnectedNodeAcknowledged,omitempty"`
	// Indicates whether or not the response should only include fields necessary for rendering the NiFi User Interface. As such, when this value is set to true, some fields may be returned as null values, and the selected fields may change at any time without notice. As a result, this value should not be set to true by any client other than the UI.
	UiOnly *bool `json:"uiOnly,omitempty"`
}

// NewUpdateControllerServiceReferenceRequestEntity instantiates a new UpdateControllerServiceReferenceRequestEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateControllerServiceReferenceRequestEntity() *UpdateControllerServiceReferenceRequestEntity {
	this := UpdateControllerServiceReferenceRequestEntity{}
	return &this
}

// NewUpdateControllerServiceReferenceRequestEntityWithDefaults instantiates a new UpdateControllerServiceReferenceRequestEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateControllerServiceReferenceRequestEntityWithDefaults() *UpdateControllerServiceReferenceRequestEntity {
	this := UpdateControllerServiceReferenceRequestEntity{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UpdateControllerServiceReferenceRequestEntity) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateControllerServiceReferenceRequestEntity) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UpdateControllerServiceReferenceRequestEntity) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UpdateControllerServiceReferenceRequestEntity) SetId(v string) {
	o.Id = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *UpdateControllerServiceReferenceRequestEntity) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateControllerServiceReferenceRequestEntity) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *UpdateControllerServiceReferenceRequestEntity) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *UpdateControllerServiceReferenceRequestEntity) SetState(v string) {
	o.State = &v
}

// GetReferencingComponentRevisions returns the ReferencingComponentRevisions field value if set, zero value otherwise.
func (o *UpdateControllerServiceReferenceRequestEntity) GetReferencingComponentRevisions() map[string]RevisionDTO {
	if o == nil || IsNil(o.ReferencingComponentRevisions) {
		var ret map[string]RevisionDTO
		return ret
	}
	return *o.ReferencingComponentRevisions
}

// GetReferencingComponentRevisionsOk returns a tuple with the ReferencingComponentRevisions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateControllerServiceReferenceRequestEntity) GetReferencingComponentRevisionsOk() (*map[string]RevisionDTO, bool) {
	if o == nil || IsNil(o.ReferencingComponentRevisions) {
		return nil, false
	}
	return o.ReferencingComponentRevisions, true
}

// HasReferencingComponentRevisions returns a boolean if a field has been set.
func (o *UpdateControllerServiceReferenceRequestEntity) HasReferencingComponentRevisions() bool {
	if o != nil && !IsNil(o.ReferencingComponentRevisions) {
		return true
	}

	return false
}

// SetReferencingComponentRevisions gets a reference to the given map[string]RevisionDTO and assigns it to the ReferencingComponentRevisions field.
func (o *UpdateControllerServiceReferenceRequestEntity) SetReferencingComponentRevisions(v map[string]RevisionDTO) {
	o.ReferencingComponentRevisions = &v
}

// GetDisconnectedNodeAcknowledged returns the DisconnectedNodeAcknowledged field value if set, zero value otherwise.
func (o *UpdateControllerServiceReferenceRequestEntity) GetDisconnectedNodeAcknowledged() bool {
	if o == nil || IsNil(o.DisconnectedNodeAcknowledged) {
		var ret bool
		return ret
	}
	return *o.DisconnectedNodeAcknowledged
}

// GetDisconnectedNodeAcknowledgedOk returns a tuple with the DisconnectedNodeAcknowledged field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateControllerServiceReferenceRequestEntity) GetDisconnectedNodeAcknowledgedOk() (*bool, bool) {
	if o == nil || IsNil(o.DisconnectedNodeAcknowledged) {
		return nil, false
	}
	return o.DisconnectedNodeAcknowledged, true
}

// HasDisconnectedNodeAcknowledged returns a boolean if a field has been set.
func (o *UpdateControllerServiceReferenceRequestEntity) HasDisconnectedNodeAcknowledged() bool {
	if o != nil && !IsNil(o.DisconnectedNodeAcknowledged) {
		return true
	}

	return false
}

// SetDisconnectedNodeAcknowledged gets a reference to the given bool and assigns it to the DisconnectedNodeAcknowledged field.
func (o *UpdateControllerServiceReferenceRequestEntity) SetDisconnectedNodeAcknowledged(v bool) {
	o.DisconnectedNodeAcknowledged = &v
}

// GetUiOnly returns the UiOnly field value if set, zero value otherwise.
func (o *UpdateControllerServiceReferenceRequestEntity) GetUiOnly() bool {
	if o == nil || IsNil(o.UiOnly) {
		var ret bool
		return ret
	}
	return *o.UiOnly
}

// GetUiOnlyOk returns a tuple with the UiOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateControllerServiceReferenceRequestEntity) GetUiOnlyOk() (*bool, bool) {
	if o == nil || IsNil(o.UiOnly) {
		return nil, false
	}
	return o.UiOnly, true
}

// HasUiOnly returns a boolean if a field has been set.
func (o *UpdateControllerServiceReferenceRequestEntity) HasUiOnly() bool {
	if o != nil && !IsNil(o.UiOnly) {
		return true
	}

	return false
}

// SetUiOnly gets a reference to the given bool and assigns it to the UiOnly field.
func (o *UpdateControllerServiceReferenceRequestEntity) SetUiOnly(v bool) {
	o.UiOnly = &v
}

func (o UpdateControllerServiceReferenceRequestEntity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateControllerServiceReferenceRequestEntity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.ReferencingComponentRevisions) {
		toSerialize["referencingComponentRevisions"] = o.ReferencingComponentRevisions
	}
	if !IsNil(o.DisconnectedNodeAcknowledged) {
		toSerialize["disconnectedNodeAcknowledged"] = o.DisconnectedNodeAcknowledged
	}
	if !IsNil(o.UiOnly) {
		toSerialize["uiOnly"] = o.UiOnly
	}
	return toSerialize, nil
}

type NullableUpdateControllerServiceReferenceRequestEntity struct {
	value *UpdateControllerServiceReferenceRequestEntity
	isSet bool
}

func (v NullableUpdateControllerServiceReferenceRequestEntity) Get() *UpdateControllerServiceReferenceRequestEntity {
	return v.value
}

func (v *NullableUpdateControllerServiceReferenceRequestEntity) Set(val *UpdateControllerServiceReferenceRequestEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateControllerServiceReferenceRequestEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateControllerServiceReferenceRequestEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateControllerServiceReferenceRequestEntity(val *UpdateControllerServiceReferenceRequestEntity) *NullableUpdateControllerServiceReferenceRequestEntity {
	return &NullableUpdateControllerServiceReferenceRequestEntity{value: val, isSet: true}
}

func (v NullableUpdateControllerServiceReferenceRequestEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateControllerServiceReferenceRequestEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


